CREATE TABLE Lecture (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL
);

ALTER TABLE Lecture ADD CONSTRAINT FK_USER_ON_LECTURE FOREIGN KEY (user_id) REFERENCES User (id);
ALTER TABLE Lecture ADD CONSTRAINT FK_COURSE_ON_LECTURE FOREIGN KEY (course_id) REFERENCES Course (id);
