CREATE TABLE Video (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    video VARCHAR(100) NOT NULL UNIQUE,
    lecture_id BIGINT NOT NULL
);

ALTER TABLE Video ADD CONSTRAINT FK_LECTURE_ON_VIDEO FOREIGN KEY (lecture_id) REFERENCES Lecture (id);
